[theme]
primaryColor = "#FF5E62"
backgroundColor = "#0C0C0F"
secondaryBackgroundColor = "#16161B"
textColor = "#F3F4F6"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = false
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 25
